version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    # install itself with pip install .
    - method: pip
      path: .
      extra_requirements:
        - docs
formats:
  - epub
  - htmlzip
  # TODO: evaluate, see https://github.com/jupyter-server/jupyter_server/issues/1378
  # - pdf
